version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      # dockerfile: .devcontainer/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    # volumes:
    #   - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    network_mode: host
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

# DB_17 is provided as a means to stand up a postgres_17 database. I would hope we'll move to postgres_18 eventually.
  # db_17:
  #   image: postgres:17
  #   restart: unless-stopped
  #   volumes: 
  #     - postgres-data:/var/lib/postgresql/data
  #     - ./migration:/docker-entrypoint-initdb.d:ro  # This mounts the hacksapce-mgmt/migration folder to the postgresql container and initialises the hackspace database with all required tables using inserted scripts.
  #   environment:
  #     POSTGRES_HOST: localhost
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: hackspace
  #     POSTGRES_PASSWORD: postgres  # pass in a secret here.
  #   ports:
  #     - 5432:5432
  #   network_mode: host

  db:
    image: postgres:18
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./migration:/docker-entrypoint-initdb.d:ro  # This mounts the hacksapce-mgmt/migration folder to the postgresql container and initialises the hackspace database with all required tables using inserted scripts.
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_DB: hackspace
      POSTGRES_PASSWORD: postgres  # pass in a secret here.
    ports:
      - 5432:5432
    network_mode: host

volumes:
  postgres-data:
